"""
Self-play data factory for crewbot.

Runs many games of The Crew across the 50-mission ladder and logs every decision
as (observation, legal-move mask, action, team reward, mission). This is the
crewbot analog of autoresearch's data-download step: a one-time (long-running)
job that fills ~/.cache/crewbot/data with training shards. Default runtime is
24 hours, parallelized across CPU cores.

Bootstrap data is generated by the cooperative heuristic in crew_engine with
epsilon-exploration. For the AlphaZero-style improvement loop, pass
--policy-ckpt to generate data with a trained network instead (see README).

Usage:
    python selfplay.py --hours 24 --workers $(nproc)
    python selfplay.py --hours 0.05 --workers 4        # quick smoke test
    python selfplay.py --policy-ckpt ~/.cache/crewbot/model.pt --epsilon 0.25
"""

import os
import time
import argparse
import numpy as np
import multiprocessing as mp

import crew_engine as E

SHARD_GAMES = 4000          # games per shard file
PROGRESS_EVERY = 20000      # games between progress prints (per worker 0)


def make_action_fn(policy_ckpt, epsilon, rng):
    """Return action_fn(state)->card. Heuristic by default; network if given."""
    if not policy_ckpt:
        return lambda s: E.heuristic_action(s, rng, epsilon=epsilon)

    # Lazy torch import so the heuristic path needs no torch.
    import torch
    from train import build_model  # model definition lives in the editable file
    model = build_model()
    model.load_state_dict(torch.load(policy_ckpt, map_location="cpu"))
    model.eval()

    @torch.no_grad()
    def net_fn(s):
        legal = E.legal_actions(s)
        if rng.random() < epsilon:
            return int(legal[rng.integers(len(legal))])
        obs = torch.from_numpy(E.observe(s)).float().unsqueeze(0)
        mask = torch.from_numpy(E.legal_mask(s)).unsqueeze(0)
        logits, _ = model(obs)
        logits = logits.masked_fill(mask == 0, float("-inf"))
        return int(logits.argmax(dim=-1).item())

    return net_fn


def worker(wid, deadline, max_decisions, counter, lock, seed, policy_ckpt, epsilon):
    rng = np.random.default_rng(seed)
    action_fn = make_action_fn(policy_ckpt, epsilon, rng)

    obs_buf, act_buf, legal_buf, rew_buf, mis_buf = [], [], [], [], []
    games = wins = shard_idx = 0
    t0 = time.time()

    def flush():
        nonlocal shard_idx, obs_buf, act_buf, legal_buf, rew_buf, mis_buf
        if not obs_buf:
            return
        path = os.path.join(E.DATA_DIR, f"shard_w{wid:02d}_{shard_idx:05d}.npz")
        np.savez_compressed(
            path,
            obs=np.asarray(obs_buf, dtype=np.float16),
            act=np.asarray(act_buf, dtype=np.int8),
            legal=np.asarray(legal_buf, dtype=np.uint8),
            rew=np.asarray(rew_buf, dtype=np.float16),
            mission=np.asarray(mis_buf, dtype=np.int8),
        )
        with lock:
            counter.value += len(obs_buf)
        shard_idx += 1
        obs_buf, act_buf, legal_buf, rew_buf, mis_buf = [], [], [], [], []

    while time.time() < deadline and counter.value < max_decisions:
        mission_id = int(rng.integers(1, 51))
        s = E.new_game(rng, mission_id)
        traj = []
        steps = 0
        while not s.done and steps < E.TOTAL_TRICKS * E.N_PLAYERS:
            obs = E.observe(s)
            mask = E.legal_mask(s)
            a = action_fn(s)
            if mask[a] == 0:
                a = E.legal_actions(s)[0]
            traj.append((obs, a, mask))
            E.step(s, a)
            steps += 1

        reward = 1.0 if s.success else 0.0
        for obs, a, mask in traj:
            obs_buf.append(obs)
            act_buf.append(a)
            legal_buf.append(mask)
            rew_buf.append(reward)
            mis_buf.append(mission_id)
        games += 1
        wins += int(s.success)

        if games % SHARD_GAMES == 0:
            flush()
        if wid == 0 and games % PROGRESS_EVERY == 0:
            elapsed = time.time() - t0
            gps = games / max(elapsed, 1e-9)
            print(f"[w0] {games:,} games | win {wins/games:.3f} | "
                  f"{gps:.0f} games/s/worker | total decisions {counter.value:,} | "
                  f"{elapsed/3600:.2f}h elapsed", flush=True)

    flush()
    return games, wins


def main():
    ap = argparse.ArgumentParser(description="Generate self-play data for crewbot")
    ap.add_argument("--hours", type=float, default=24.0, help="wall-clock runtime budget")
    ap.add_argument("--workers", type=int, default=max(1, mp.cpu_count() - 1))
    ap.add_argument("--max-decisions", type=int, default=80_000_000,
                    help="hard cap on logged decisions (~1KB each) to bound disk")
    ap.add_argument("--epsilon", type=float, default=0.15, help="exploration rate")
    ap.add_argument("--policy-ckpt", type=str, default="",
                    help="optional trained checkpoint to generate stronger data")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    os.makedirs(E.DATA_DIR, exist_ok=True)
    deadline = time.time() + args.hours * 3600
    print(f"Self-play: {args.workers} workers, budget {args.hours:.3f}h, "
          f"cap {args.max_decisions:,} decisions")
    print(f"Writing shards to {E.DATA_DIR}")
    print(f"OBS_DIM={E.OBS_DIM}  ACT_DIM={E.ACT_DIM}")

    ctx = mp.get_context("spawn")
    counter = ctx.Value("q", 0)   # signed long long
    lock = ctx.Lock()
    procs = []
    for wid in range(args.workers):
        p = ctx.Process(target=worker, args=(
            wid, deadline, args.max_decisions, counter, lock,
            args.seed + 1000 * wid + 1, args.policy_ckpt, args.epsilon))
        p.start()
        procs.append(p)
    for p in procs:
        p.join()

    print(f"Done. Total decisions logged: {counter.value:,}")
    print(f"Shards in {E.DATA_DIR}")


if __name__ == "__main__":
    main()
